from typing import List, Dict, Any, Optional
import logging
import json
from src.models.history import AccountHistory
from src.models.common import PatchOperation
from src.client import ocs_client

logger = logging.getLogger(__name__)

async def create_account_history(
    entityId: str,
    entityType: str,
    description: str,
    direction: Optional[str] = None,
    reason: Optional[str] = None,
    status: Optional[str] = None,
    transaction_id: Optional[str] = None
) -> Dict[str, Any]:
    """
**Tool Name:** Create Account History Entry

**Purpose:** Records an AI agent interaction with a subscriber account in the OCS system. This tool creates an audit trail entry documenting automated actions, recommendations, or interactions performed by the AI assistant.

**CRITICAL: Channel Requirement**
- **ALWAYS** set `channel` field to **"AI-AGENT"** for all AI assistant interactions
- This identifies the interaction source as an automated AI agent rather than human operators or other systems
- Required for proper auditing, compliance tracking, and interaction analytics

**Required Parameters:**
- `entityId` (string): The unique identifier of the entity being interacted with
  - For subscriber interactions: Use subscriberId (obtained from `create_subscriber` or `lookup_subscriber`)
  - For subscription interactions: Use subscriptionId
  - For group interactions: Use groupId

- `entityType` (string): The type of entity being tracked. Must be one of:
  - **"SUBSCRIBER"** - For subscriber account interactions (most common)
  - **"GROUP"** - For group account interactions
  - **"ACCOUNT"** - For general account-level interactions

- `description` (string): Human-readable description of the AI agent action or interaction
  - Examples:
    - "AI assistant created POSTPAID subscriber account"
    - "AI assistant updated subscriber address information"
    - "AI assistant provided billing cycle information to user"
    - "AI assistant looked up subscriber details for customer inquiry"
    - "AI assistant performed subscriber account deletion"

**Optional Parameters:**
- `direction` (string): Interaction direction (e.g., "inbound", "outbound", "automated")
  - Recommended: "automated" for AI agent interactions
  
- `reason` (string): Business reason for the interaction
  - Examples: "Customer Request", "Account Management", "Information Query", "Data Update"

- `status` (string): Current status of the interaction
  - Examples: "completed", "in-progress", "failed", "pending"
  - Recommended: "completed" for successfully executed AI actions

- `transaction_id` (string): Optional custom transaction ID for tracking correlated operations
  - If not provided, a unique transaction ID will be auto-generated

**Auto-Generated Fields:**
- `interactionId`: Unique identifier for this history entry (generated by OCS API)
- `creationDate`: Timestamp when the entry was created (set by OCS API)
- `channel`: Automatically set to "AI-AGENT" by this tool
- `interactionDate.startDateTime`: Set to current timestamp
- `interactionDate.endDateTime`: Set to current timestamp

**Returns:**
Complete account history entry object including:
- Generated `interactionId`
- Timestamp information (`creationDate`, `interactionDate`)
- All provided fields
- System-assigned metadata

**Use Cases:**
1. **Audit Trail Creation**: Document every AI agent action for compliance
2. **Customer Service History**: Track AI-assisted customer interactions
3. **Automated Action Logging**: Record programmatic account modifications
4. **Analytics and Reporting**: Enable analysis of AI agent effectiveness
5. **Troubleshooting**: Maintain detailed logs for debugging issues

**Workflow Pattern:**
```
IMPORTANT: Most OCS API operations (create/update/delete subscriber, subscriptions, etc.) 
automatically generate account history entries. This tool should ONLY be used for:
- Recording additional AI assistant commentary or analysis
- Logging compound operations that span multiple API calls
- Creating custom audit entries for business logic not captured by API

BEFORE using this tool:
1. AI agent performs action (create/update/delete subscriber, etc.)
2. **ASK USER**: "Would you like me to create an additional account history entry for this action?"
3. If user confirms, then call create_account_history with:
   - Same subscriberId/entityId as the action
   - Set entityType = "SUBSCRIBER" for subscriber operations
   - Provide clear description of what was done
   - Set status = "completed" if action succeeded

DO NOT automatically create history entries without user confirmation, as the OCS API 
already creates them for standard operations.
```

**Example Scenarios:**

*Scenario 1: Recording Subscriber Creation*
```
entityId: "sub_abc123" (newly created subscriberId)
entityType: "SUBSCRIBER"
description: "AI assistant created POSTPAID subscriber for Stevie Wonder"
direction: "automated"
reason: "Customer Onboarding Request"
status: "completed"
```

*Scenario 2: Recording Address Update*
```
entityId: "sub_abc123" (existing subscriberId)
entityType: "SUBSCRIBER"
description: "AI assistant updated billing address to Hainestrasse 75/1/5"
direction: "automated"
reason: "Customer Address Change Request"
status: "completed"
```

*Scenario 3: Recording Information Query*
```
entityId: "sub_abc123"
entityType: "SUBSCRIBER"
description: "AI assistant retrieved account details for customer inquiry"
direction: "inbound"
reason: "Customer Service Request"
status: "completed"
```

**Important Notes:**
- **Most OCS operations automatically create account history entries** - avoid duplication
- **Always ask the user first** before creating an account history entry
- Only create entries for additional context not captured by automatic API logging
- Use consistent, descriptive language in the description field
- Include customer/subscriber names in descriptions when appropriate
- Set proper entityType to enable entity-specific history filtering
- The channel "AI-AGENT" is automatically set - do not override it

**Error Handling:**
- **400 Bad Request**: Missing required fields or invalid data format
  - Verify entityType is one of: SUBSCRIBER, GROUP, ACCOUNT
  - Ensure entityId format is valid
- **409 Conflict**: Duplicate interactionId (rare, auto-generated should be unique)
- Check that entityId exists in the system before creating history

**Best Practices:**
✓ Create history entries immediately after successful operations
✓ Use past tense in descriptions ("created", "updated", "deleted")
✓ Include relevant context (subscriber names, changed fields, etc.)
✓ Set status="completed" for successful operations
✓ Use consistent reason categories across similar operations
✓ Leverage transaction_id to link related operations together
    """
    from datetime import datetime
    import uuid
    from src.models.history import AccountHistory
    from src.models.common import EntityType
    
    # Auto-generate interactionId if not provided
    interaction_id = f"AI-{str(uuid.uuid4())[:8]}"
    current_time = datetime.utcnow()
    
    # Build the account history object with AI-AGENT channel
    history_data = AccountHistory(
        interactionId=interaction_id,
        entityId=entityId,
        entityType=EntityType(entityType),
        creationDate=current_time,
        description=description,
        direction=direction or "automated",
        reason=reason,
        status=status or "completed",
        statusChangeDate=current_time if status else None,
        channel="AI-AGENT",  # CRITICAL: Always set to AI-AGENT for AI interactions
        interactionDate={
            "startDateTime": current_time,
            "endDateTime": current_time
        }
    )
    
    data = history_data.model_dump(mode='json', exclude_none=True)
    logger.info(f"create_account_history called with data: {data}")
    
    result = await ocs_client.request(
        method="POST",
        endpoint="/accountHistory",
        json=data,
        transaction_id=transaction_id
    )
    
    logger.info(f"create_account_history result: {result}")
    return result

async def get_account_history(
    entityId: str, 
    limit: int = 10, 
    offset: int = 0
) -> str:
    """
**Tool Name:** Get Account History

**Purpose:** Retrieves the account history for a subscriber using their unique subscriber identifier (entityId). This tool returns a paginated chronological list of all account-related events, transactions, and state changes associated with the subscriber.

**Required Parameters:**
- `entityId` (string): The unique subscriber identifier (subscriberId)
  - This is the same subscriberId returned when creating a subscriber or obtained via the `lookup_subscriber` tool

**Optional Parameters:**
- `limit` (integer): Maximum number of history entries to return per request
  - **Default:** 10
  - **Range:** 1-100
  - Use this to control page size for pagination
- `offset` (integer): Number of entries to skip (for pagination)
  - **Default:** 0
  - **Minimum:** 0
  - Use this to navigate through multiple pages of results

**Pagination:**
To retrieve all history entries for a subscriber with many events:
1. First call: `get_account_history(entityId, limit=100, offset=0)` - Returns entries 0-99
2. Second call: `get_account_history(entityId, limit=100, offset=100)` - Returns entries 100-199
3. Continue incrementing offset by limit until fewer results are returned than requested

**Returns:**
A list of account history entries in JSON format, where each entry typically includes:
- Event timestamp/date
- Event type (e.g., account creation, balance changes, state transitions, service activations)
- Transaction details
- Status changes
- User/system actions performed
- Any relevant metadata or context for the event

**Use Cases:**
- Auditing subscriber account activity
- Troubleshooting billing or service issues
- Compliance and regulatory reporting
- Customer service inquiries about past transactions
- Investigating account state changes
- Tracking subscriber lifecycle events

**Workflow:**
1. Obtain the subscriberId using `create_subscriber` or `lookup_subscriber`
2. Call this tool with appropriate pagination parameters
3. Review chronological events to understand account activity
4. Use offset to retrieve additional pages if needed

**Important Notes:**
- History entries are typically returned in chronological order
- The completeness of history depends on system retention policies
- Empty results indicate no recorded history for the subscriber
- For subscribers with extensive history, use pagination to retrieve all entries efficiently

**Error Handling:**
- Invalid or non-existent subscriberId may return an empty list or error status
- Ensure the subscriberId format is correct before querying
- Offset beyond available entries returns empty list
    """
    params = {
        "limit": limit,
        "offset": offset
    }
    logger.info(f"get_account_history called for subscriber '{entityId}' with limit={limit}, offset={offset}")
    result = await ocs_client.request(
        method="GET",
        endpoint=f"/accountHistory/entityId/{entityId}",
        params=params
    )
    logger.info(f"get_account_history result: '{result}'")
    
    # Ensure we return the list as a properly formatted JSON string for MCP display
    if isinstance(result, list):
        return json.dumps(result, indent=2)
    return result
